TARGET=OpenImageIOTests
SOURCES+=main.cpp
CONFIG+=c++14
INCLUDEPATH+=/usr/local/include
LIBS+= -L/usr/local/lib -lOpenImageIO -lOpenImageIO_Util
CONFIG -=app_bundle
LIBS+= -L/usr/local/lib -lgtest 
#LIBS+=`pkg-config  --static --libs libtiff-4`
#LIBS+=-ltiff -ljpeg -lz
